### ISSUE TITLE
Can't install/uninstall template packages

### ISSUE THREAD

**Issue by kdiogenes** [nhaouari/obsidian-textgenerator-plugin#170] opened 2023-05-27 21:07 UTC
I'm using the latest version (0.3.18) and when I click on the Template Package Manager icon I can see the packages, but when I click on some of them I can see that the screen layout changes, so the packages stay on the left column and its options on the right, but almost immediately this dialog stay totally blank. Below are screenshots:

After accessing the Template Package Manager:
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/943369/b6b8c179-4972-40a3-9fbf-2fb5468d6c65)

After clicking on any package:
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/943369/1bbcb708-d663-4066-844c-9f1870559e93)

I already tried re-installing the plugin, but the problem persists.

**Comment by kdiogenes** [comment] 2023-05-27 21:28
I discovered that is a kind of conflict with the Readwise Official plugin. Now I can see the screen to install/uninstall prompts:
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/943369/15769496-2768-4cd2-98b1-41b15bcfc545)

But I'm not able to uninstall any prompt package. I click, and a folder is created on textgenerator/prompts/trash/dalle-2, but the package is still marked as installed.

**Comment by kdiogenes** [comment] 2023-05-27 21:35
While trying to solve the issue I deleted all the prompts on the textgenerator obsidian folder. After downloading the prompts collection from their respective repository and populating these folders I was able to uninstall them. I think that this can be better handled by the plugin, so I'm leaving this open.

**Comment by turnerll** [comment] 2023-06-14 22:22
> 

same here

**Comment by turnerll** [comment] 2023-06-14 22:22
It doesn't matter if I change the folder location or leave it as default when I try to install the package manager it just blanks out and quits

**Comment by marvinwu** [comment] 2023-06-29 03:33
Same blank screen on template manager here, inspired by @kdiogenes  comment, I found a work around:

* turned off all other community plugins and left only with text generator
* installs the needed prompt package.
* turned all other plugins back on

seems indeed caused by plugin conflict, but I didn't know exactly which one( I didn't have readwise plugin though)

**Comment by davejorg** [comment] 2023-07-01 20:25
For me it was the "Metadata Menu" plugin. 
I didn't have the Readwise plugin installed.

I left all other plugins turned on, here is the list of plugins I have installed together that did not cause this to happen besides the Metadata Menu plugin:
- workspaces-plus
- url-into-selection
- tag-wrangler
- templater-obsidian
- text-extractor
- quickadd
- recent-files-obsidian
- table-editor-obsidian
- obsidian-tasks-plugin
- obsidian-textgenerator-plugin
- obsidian-zoom
- omnisearch
- obsidian-reminder-plugin
- obsidian-style-settings
- obsidian-minimal-settings
- obsidian-outliner
- obsidian-relative-line-numbers
- obsidian-hover-editor
- obsidian-local-rest-api
- obsidian-custom-frames
- obsidian-git
- obsidian-advanced-uri
- obsidian-auto-link-title
- nldates-obsidian
- note-refactor-obsidian
- metaedit
- **metadata-menu** - THIS WAS DISABLED AND CAUSING THE ISSUE
- file-tree-alternative
- heatmap-calendar
- execute-code
- dbfolder
- dataview
- code-block-copy
- cmdr
- cm-editor-syntax-highlight-obsidian
- calendar
- buttons

![metadate-menu](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/9435431/a604f3ce-b29e-4b9c-bc6f-ec0495e342eb)

Temporarily disable Metadata Menu and it will hopefully work for you.

**Comment by piersdd** [comment] 2023-08-23 21:20
> For me it was the "Metadata Menu" plugin. I didn't have the Readwise plugin installed. All other plugins were turned on. Here is the list of plugins I have installed together that did not cause this to happen besides the Metadata Menu plugin:
> 
> * workspaces-plus
> * url-into-selection
> * tag-wrangler
> * templater-obsidian
> * text-extractor
> * quickadd
> * recent-files-obsidian
> * table-editor-obsidian
> * obsidian-tasks-plugin
> * obsidian-textgenerator-plugin
> * obsidian-zoom
> * omnisearch
> * obsidian-reminder-plugin
> * obsidian-style-settings
> * obsidian-minimal-settings
> * obsidian-outliner
> * obsidian-relative-line-numbers
> * obsidian-hover-editor
> * obsidian-local-rest-api
> * obsidian-custom-frames
> * obsidian-git
> * obsidian-advanced-uri
> * obsidian-auto-link-title
> * nldates-obsidian
> * note-refactor-obsidian
> * metaedit
> * **metadata-menu** - THIS WAS DISABLED AND CAUSING THE ISSUE
> * file-tree-alternative
> * heatmap-calendar
> * execute-code
> * dbfolder
> * dataview
> * code-block-copy
> * cmdr
> * cm-editor-syntax-highlight-obsidian
> * calendar
> * buttons
> 
> ![metadate-menu](https://user-images.githubusercontent.com/9435431/250305835-a604f3ce-b29e-4b9c-bc6f-ec0495e342eb.jpg)
> 
> Temporarily disable Metadata Menu and it will hopefully work for you.

this worked for me. thanks

**Comment by g1ronn1mo** [comment] 2023-10-17 17:20
## Problem

I accidentally deleted the folder where the files re located, now the popup thinks they are installed, and I can not reinstall them. When I try to uninstall them empty folders get added to the trash. 

## Solution

Trace the folder structure and set it to uninstall, if the folder is not present.

**Comment by Smitty010** [comment] 2023-10-28 21:47
I'm having the same problem.  I'm running Text Generator 0.3.20

I click on the "Text Generator: Templates Package Manager" button.  I see the following (which I think is what should happen):
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/3760075/221baa4c-9fe1-4aa7-8eb4-3f8baba1b568)
I cleared the developer console and then clicked on the "Huggingface Prompts Package" button.  I can see that another dialog with the prompt packages on the left side briefly shows and then the screen goes blank.

Here's a copy of the stack trace the occurs.
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at updateElLinks (plugin:metadata-menu:11924:33)
    at eval (plugin:metadata-menu:12136:7)
    at t.render (app.js:1:1231657)
    at t.renderMarkdown (app.js:1:1230972)
    at PackageManager.eval (plugin:obsidian-textgenerator-plugin:57799:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-textgenerator-plugin:65:24)
eval @ plugin:obsidian-textgenerator-plugin:57804
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
eval @ plugin:obsidian-textgenerator-plugin:78
__async @ plugin:obsidian-textgenerator-plugin:62
getReadme @ plugin:obsidian-textgenerator-plugin:57792
eval @ plugin:obsidian-textgenerator-plugin:57990
commitHookEffectListMount @ plugin:obsidian-textgenerator-plugin:21271
commitPassiveMountOnFiber @ plugin:obsidian-textgenerator-plugin:22513
commitPassiveMountEffects_complete @ plugin:obsidian-textgenerator-plugin:22481
commitPassiveMountEffects_begin @ plugin:obsidian-textgenerator-plugin:22471
commitPassiveMountEffects @ plugin:obsidian-textgenerator-plugin:22461
flushPassiveEffectsImpl @ plugin:obsidian-textgenerator-plugin:23814
flushPassiveEffects @ plugin:obsidian-textgenerator-plugin:23771
commitRootImpl @ plugin:obsidian-textgenerator-plugin:23740
commitRoot @ plugin:obsidian-textgenerator-plugin:23601
performSyncWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23220
flushSyncCallbacks @ plugin:obsidian-textgenerator-plugin:13709
eval @ plugin:obsidian-textgenerator-plugin:22953
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:204
runMicrotask @ node:internal/process/task_queues:137
plugin:obsidian-textgenerator-plugin:58079 Uncaught TypeError: Cannot read properties of undefined (reading 'innerHTML')
    at getTemplateDetails (plugin:obsidian-textgenerator-plugin:58079:23)
    at TemplateDetails (plugin:obsidian-textgenerator-plugin:57977:23)
    at renderWithHooks (plugin:obsidian-textgenerator-plugin:16665:26)
    at updateFunctionComponent (plugin:obsidian-textgenerator-plugin:19028:28)
    at beginWork (plugin:obsidian-textgenerator-plugin:20295:22)
    at HTMLUnknownElement.callCallback2 (plugin:obsidian-textgenerator-plugin:8508:22)
    at Object.invokeGuardedCallbackDev (plugin:obsidian-textgenerator-plugin:8533:24)
    at invokeGuardedCallback (plugin:obsidian-textgenerator-plugin:8567:39)
    at beginWork$1 (plugin:obsidian-textgenerator-plugin:24089:15)
    at performUnitOfWork (plugin:obsidian-textgenerator-plugin:23525:21)
    at workLoopSync (plugin:obsidian-textgenerator-plugin:23461:13)
    at renderRootSync (plugin:obsidian-textgenerator-plugin:23440:15)
    at performConcurrentWorkOnRoot (plugin:obsidian-textgenerator-plugin:23004:83)
    at workLoop (plugin:obsidian-textgenerator-plugin:5254:42)
    at flushWork (plugin:obsidian-textgenerator-plugin:5233:22)
    at Immediate.performWorkUntilDeadline [as _onImmediate] (plugin:obsidian-textgenerator-plugin:5441:29)
    at process.processImmediate (node:internal/timers:476:21)
getTemplateDetails @ plugin:obsidian-textgenerator-plugin:58079
TemplateDetails @ plugin:obsidian-textgenerator-plugin:57977
renderWithHooks @ plugin:obsidian-textgenerator-plugin:16665
updateFunctionComponent @ plugin:obsidian-textgenerator-plugin:19028
beginWork @ plugin:obsidian-textgenerator-plugin:20295
callCallback2 @ plugin:obsidian-textgenerator-plugin:8508
invokeGuardedCallbackDev @ plugin:obsidian-textgenerator-plugin:8533
invokeGuardedCallback @ plugin:obsidian-textgenerator-plugin:8567
beginWork$1 @ plugin:obsidian-textgenerator-plugin:24089
performUnitOfWork @ plugin:obsidian-textgenerator-plugin:23525
workLoopSync @ plugin:obsidian-textgenerator-plugin:23461
renderRootSync @ plugin:obsidian-textgenerator-plugin:23440
performConcurrentWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23004
workLoop @ plugin:obsidian-textgenerator-plugin:5254
flushWork @ plugin:obsidian-textgenerator-plugin:5233
performWorkUntilDeadline @ plugin:obsidian-textgenerator-plugin:5441
processImmediate @ node:internal/timers:476
plugin:obsidian-textgenerator-plugin:58079 Uncaught TypeError: Cannot read properties of undefined (reading 'innerHTML')
    at getTemplateDetails (plugin:obsidian-textgenerator-plugin:58079:23)
    at TemplateDetails (plugin:obsidian-textgenerator-plugin:57977:23)
    at renderWithHooks (plugin:obsidian-textgenerator-plugin:16665:26)
    at updateFunctionComponent (plugin:obsidian-textgenerator-plugin:19028:28)
    at beginWork (plugin:obsidian-textgenerator-plugin:20295:22)
    at HTMLUnknownElement.callCallback2 (plugin:obsidian-textgenerator-plugin:8508:22)
    at Object.invokeGuardedCallbackDev (plugin:obsidian-textgenerator-plugin:8533:24)
    at invokeGuardedCallback (plugin:obsidian-textgenerator-plugin:8567:39)
    at beginWork$1 (plugin:obsidian-textgenerator-plugin:24089:15)
    at performUnitOfWork (plugin:obsidian-textgenerator-plugin:23525:21)
    at workLoopSync (plugin:obsidian-textgenerator-plugin:23461:13)
    at renderRootSync (plugin:obsidian-textgenerator-plugin:23440:15)
    at recoverFromConcurrentError (plugin:obsidian-textgenerator-plugin:23062:28)
    at performConcurrentWorkOnRoot (plugin:obsidian-textgenerator-plugin:23010:30)
    at workLoop (plugin:obsidian-textgenerator-plugin:5254:42)
    at flushWork (plugin:obsidian-textgenerator-plugin:5233:22)
    at Immediate.performWorkUntilDeadline [as _onImmediate] (plugin:obsidian-textgenerator-plugin:5441:29)
    at process.processImmediate (node:internal/timers:476:21)
getTemplateDetails @ plugin:obsidian-textgenerator-plugin:58079
TemplateDetails @ plugin:obsidian-textgenerator-plugin:57977
renderWithHooks @ plugin:obsidian-textgenerator-plugin:16665
updateFunctionComponent @ plugin:obsidian-textgenerator-plugin:19028
beginWork @ plugin:obsidian-textgenerator-plugin:20295
callCallback2 @ plugin:obsidian-textgenerator-plugin:8508
invokeGuardedCallbackDev @ plugin:obsidian-textgenerator-plugin:8533
invokeGuardedCallback @ plugin:obsidian-textgenerator-plugin:8567
beginWork$1 @ plugin:obsidian-textgenerator-plugin:24089
performUnitOfWork @ plugin:obsidian-textgenerator-plugin:23525
workLoopSync @ plugin:obsidian-textgenerator-plugin:23461
renderRootSync @ plugin:obsidian-textgenerator-plugin:23440
recoverFromConcurrentError @ plugin:obsidian-textgenerator-plugin:23062
performConcurrentWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23010
workLoop @ plugin:obsidian-textgenerator-plugin:5254
flushWork @ plugin:obsidian-textgenerator-plugin:5233
performWorkUntilDeadline @ plugin:obsidian-textgenerator-plugin:5441
processImmediate @ node:internal/timers:476
plugin:obsidian-textgenerator-plugin:18519 The above error occurred in the <TemplateDetails> component:

    at TemplateDetails (plugin:obsidian-textgenerator-plugin:57950:3)
    at div
    at div
    at div
    at PackageManagerView (plugin:obsidian-textgenerator-plugin:58088:56)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ plugin:obsidian-textgenerator-plugin:18519
update.callback @ plugin:obsidian-textgenerator-plugin:18539
callCallback @ plugin:obsidian-textgenerator-plugin:15043
commitUpdateQueue @ plugin:obsidian-textgenerator-plugin:15060
commitLayoutEffectOnFiber @ plugin:obsidian-textgenerator-plugin:21450
commitLayoutMountEffects_complete @ plugin:obsidian-textgenerator-plugin:22332
commitLayoutEffects_begin @ plugin:obsidian-textgenerator-plugin:22321
commitLayoutEffects @ plugin:obsidian-textgenerator-plugin:22277
commitRootImpl @ plugin:obsidian-textgenerator-plugin:23677
commitRoot @ plugin:obsidian-textgenerator-plugin:23601
finishConcurrentRender @ plugin:obsidian-textgenerator-plugin:23086
performConcurrentWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23044
workLoop @ plugin:obsidian-textgenerator-plugin:5254
flushWork @ plugin:obsidian-textgenerator-plugin:5233
performWorkUntilDeadline @ plugin:obsidian-textgenerator-plugin:5441
processImmediate @ node:internal/timers:476
plugin:obsidian-textgenerator-plugin:58079 Uncaught TypeError: Cannot read properties of undefined (reading 'innerHTML')
    at getTemplateDetails (plugin:obsidian-textgenerator-plugin:58079:23)
    at TemplateDetails (plugin:obsidian-textgenerator-plugin:57977:23)
    at renderWithHooks (plugin:obsidian-textgenerator-plugin:16665:26)
    at updateFunctionComponent (plugin:obsidian-textgenerator-plugin:19028:28)
    at beginWork (plugin:obsidian-textgenerator-plugin:20295:22)
    at beginWork$1 (plugin:obsidian-textgenerator-plugin:24077:22)
    at performUnitOfWork (plugin:obsidian-textgenerator-plugin:23525:21)
    at workLoopSync (plugin:obsidian-textgenerator-plugin:23461:13)
    at renderRootSync (plugin:obsidian-textgenerator-plugin:23440:15)
    at recoverFromConcurrentError (plugin:obsidian-textgenerator-plugin:23062:28)
    at performConcurrentWorkOnRoot (plugin:obsidian-textgenerator-plugin:23010:30)
    at workLoop (plugin:obsidian-textgenerator-plugin:5254:42)
    at flushWork (plugin:obsidian-textgenerator-plugin:5233:22)
    at Immediate.performWorkUntilDeadline (plugin:obsidian-textgenerator-plugin:5441:29)
    at process.processImmediate (node:internal/timers:476:21)
getTemplateDetails @ plugin:obsidian-textgenerator-plugin:58079
TemplateDetails @ plugin:obsidian-textgenerator-plugin:57977
renderWithHooks @ plugin:obsidian-textgenerator-plugin:16665
updateFunctionComponent @ plugin:obsidian-textgenerator-plugin:19028
beginWork @ plugin:obsidian-textgenerator-plugin:20295
beginWork$1 @ plugin:obsidian-textgenerator-plugin:24077
performUnitOfWork @ plugin:obsidian-textgenerator-plugin:23525
workLoopSync @ plugin:obsidian-textgenerator-plugin:23461
renderRootSync @ plugin:obsidian-textgenerator-plugin:23440
recoverFromConcurrentError @ plugin:obsidian-textgenerator-plugin:23062
performConcurrentWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23010
workLoop @ plugin:obsidian-textgenerator-plugin:5254
flushWork @ plugin:obsidian-textgenerator-plugin:5233
performWorkUntilDeadline @ plugin:obsidian-textgenerator-plugin:5441
processImmediate @ node:internal/timers:476
plugin:dataview:19245 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lastIndexOf')
    at isDataviewDisabled (plugin:dataview:19245:39)
    at eval (plugin:dataview:19869:56)
    at t.render (app.js:1:1231657)
    at t.renderMarkdown (app.js:1:1230972)
    at PackageManager.eval (plugin:obsidian-textgenerator-plugin:57799:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-textgenerator-plugin:65:24)
isDataviewDisabled @ plugin:dataview:19245
eval @ plugin:dataview:19869
t.render @ app.js:1
t.renderMarkdown @ app.js:1
eval @ plugin:obsidian-textgenerator-plugin:57799
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
eval @ plugin:obsidian-textgenerator-plugin:78
__async @ plugin:obsidian-textgenerator-plugin:62
getReadme @ plugin:obsidian-textgenerator-plugin:57792
eval @ plugin:obsidian-textgenerator-plugin:57990
commitHookEffectListMount @ plugin:obsidian-textgenerator-plugin:21271
commitPassiveMountOnFiber @ plugin:obsidian-textgenerator-plugin:22513
commitPassiveMountEffects_complete @ plugin:obsidian-textgenerator-plugin:22481
commitPassiveMountEffects_begin @ plugin:obsidian-textgenerator-plugin:22471
commitPassiveMountEffects @ plugin:obsidian-textgenerator-plugin:22461
flushPassiveEffectsImpl @ plugin:obsidian-textgenerator-plugin:23814
flushPassiveEffects @ plugin:obsidian-textgenerator-plugin:23771
commitRootImpl @ plugin:obsidian-textgenerator-plugin:23740
commitRoot @ plugin:obsidian-textgenerator-plugin:23601
performSyncWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23220
flushSyncCallbacks @ plugin:obsidian-textgenerator-plugin:13709
eval @ plugin:obsidian-textgenerator-plugin:22953
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:204
runMicrotask @ node:internal/process/task_queues:137
plugin:metadata-menu:11924 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at updateElLinks (plugin:metadata-menu:11924:33)
    at eval (plugin:metadata-menu:12136:7)
    at t.render (app.js:1:1231657)
    at t.renderMarkdown (app.js:1:1230972)
    at PackageManager.eval (plugin:obsidian-textgenerator-plugin:57799:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-textgenerator-plugin:65:24)
updateElLinks @ plugin:metadata-menu:11924
eval @ plugin:metadata-menu:12136
t.render @ app.js:1
t.renderMarkdown @ app.js:1
eval @ plugin:obsidian-textgenerator-plugin:57799
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
eval @ plugin:obsidian-textgenerator-plugin:78
__async @ plugin:obsidian-textgenerator-plugin:62
getReadme @ plugin:obsidian-textgenerator-plugin:57792
eval @ plugin:obsidian-textgenerator-plugin:57990
commitHookEffectListMount @ plugin:obsidian-textgenerator-plugin:21271
commitPassiveMountOnFiber @ plugin:obsidian-textgenerator-plugin:22513
commitPassiveMountEffects_complete @ plugin:obsidian-textgenerator-plugin:22481
commitPassiveMountEffects_begin @ plugin:obsidian-textgenerator-plugin:22471
commitPassiveMountEffects @ plugin:obsidian-textgenerator-plugin:22461
flushPassiveEffectsImpl @ plugin:obsidian-textgenerator-plugin:23814
flushPassiveEffects @ plugin:obsidian-textgenerator-plugin:23771
commitRootImpl @ plugin:obsidian-textgenerator-plugin:23740
commitRoot @ plugin:obsidian-textgenerator-plugin:23601
performSyncWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23220
flushSyncCallbacks @ plugin:obsidian-textgenerator-plugin:13709
eval @ plugin:obsidian-textgenerator-plugin:22953
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:204
runMicrotask @ node:internal/process/task_queues:137
plugin:obsidian-textgenerator-plugin:57804 TypeError: Cannot read properties of undefined (reading 'replace')
    at updateElLinks (plugin:metadata-menu:11924:33)
    at eval (plugin:metadata-menu:12136:7)
    at t.render (app.js:1:1231657)
    at t.renderMarkdown (app.js:1:1230972)
    at PackageManager.eval (plugin:obsidian-textgenerator-plugin:57799:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-textgenerator-plugin:65:24)
eval @ plugin:obsidian-textgenerator-plugin:57804
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
eval @ plugin:obsidian-textgenerator-plugin:78
__async @ plugin:obsidian-textgenerator-plugin:62
getReadme @ plugin:obsidian-textgenerator-plugin:57792
eval @ plugin:obsidian-textgenerator-plugin:57990
commitHookEffectListMount @ plugin:obsidian-textgenerator-plugin:21271
invokePassiveEffectMountInDEV @ plugin:obsidian-textgenerator-plugin:22676
invokeEffectsInDev @ plugin:obsidian-textgenerator-plugin:24025
commitDoubleInvokeEffectsInDEV @ plugin:obsidian-textgenerator-plugin:24010
flushPassiveEffectsImpl @ plugin:obsidian-textgenerator-plugin:23827
flushPassiveEffects @ plugin:obsidian-textgenerator-plugin:23771
commitRootImpl @ plugin:obsidian-textgenerator-plugin:23740
commitRoot @ plugin:obsidian-textgenerator-plugin:23601
performSyncWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23220
flushSyncCallbacks @ plugin:obsidian-textgenerator-plugin:13709
eval @ plugin:obsidian-textgenerator-plugin:22953
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:204
runMicrotask @ node:internal/process/task_queues:137
plugin:dataview:19245 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lastIndexOf')
    at isDataviewDisabled (plugin:dataview:19245:39)
    at eval (plugin:dataview:19869:56)
    at t.render (app.js:1:1231657)
    at t.renderMarkdown (app.js:1:1230972)
    at PackageManager.eval (plugin:obsidian-textgenerator-plugin:57799:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-textgenerator-plugin:65:24)
isDataviewDisabled @ plugin:dataview:19245
eval @ plugin:dataview:19869
t.render @ app.js:1
t.renderMarkdown @ app.js:1
eval @ plugin:obsidian-textgenerator-plugin:57799
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
eval @ plugin:obsidian-textgenerator-plugin:78
__async @ plugin:obsidian-textgenerator-plugin:62
getReadme @ plugin:obsidian-textgenerator-plugin:57792
eval @ plugin:obsidian-textgenerator-plugin:57990
commitHookEffectListMount @ plugin:obsidian-textgenerator-plugin:21271
invokePassiveEffectMountInDEV @ plugin:obsidian-textgenerator-plugin:22676
invokeEffectsInDev @ plugin:obsidian-textgenerator-plugin:24025
commitDoubleInvokeEffectsInDEV @ plugin:obsidian-textgenerator-plugin:24010
flushPassiveEffectsImpl @ plugin:obsidian-textgenerator-plugin:23827
flushPassiveEffects @ plugin:obsidian-textgenerator-plugin:23771
commitRootImpl @ plugin:obsidian-textgenerator-plugin:23740
commitRoot @ plugin:obsidian-textgenerator-plugin:23601
performSyncWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23220
flushSyncCallbacks @ plugin:obsidian-textgenerator-plugin:13709
eval @ plugin:obsidian-textgenerator-plugin:22953
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:204
runMicrotask @ node:internal/process/task_queues:137
plugin:metadata-menu:11924 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at updateElLinks (plugin:metadata-menu:11924:33)
    at eval (plugin:metadata-menu:12136:7)
    at t.render (app.js:1:1231657)
    at t.renderMarkdown (app.js:1:1230972)
    at PackageManager.eval (plugin:obsidian-textgenerator-plugin:57799:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-textgenerator-plugin:65:24)
updateElLinks @ plugin:metadata-menu:11924
eval @ plugin:metadata-menu:12136
t.render @ app.js:1
t.renderMarkdown @ app.js:1
eval @ plugin:obsidian-textgenerator-plugin:57799
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
fulfilled @ plugin:obsidian-textgenerator-plugin:65
Promise.then (async)
step @ plugin:obsidian-textgenerator-plugin:77
eval @ plugin:obsidian-textgenerator-plugin:78
__async @ plugin:obsidian-textgenerator-plugin:62
getReadme @ plugin:obsidian-textgenerator-plugin:57792
eval @ plugin:obsidian-textgenerator-plugin:57990
commitHookEffectListMount @ plugin:obsidian-textgenerator-plugin:21271
invokePassiveEffectMountInDEV @ plugin:obsidian-textgenerator-plugin:22676
invokeEffectsInDev @ plugin:obsidian-textgenerator-plugin:24025
commitDoubleInvokeEffectsInDEV @ plugin:obsidian-textgenerator-plugin:24010
flushPassiveEffectsImpl @ plugin:obsidian-textgenerator-plugin:23827
flushPassiveEffects @ plugin:obsidian-textgenerator-plugin:23771
commitRootImpl @ plugin:obsidian-textgenerator-plugin:23740
commitRoot @ plugin:obsidian-textgenerator-plugin:23601
performSyncWorkOnRoot @ plugin:obsidian-textgenerator-plugin:23220
flushSyncCallbacks @ plugin:obsidian-textgenerator-plugin:13709
eval @ plugin:obsidian-textgenerator-plugin:22953
(anonymous) @ node:internal/process/task_queues:140
runInAsyncScope @ node:async_hooks:204
runMicrotask @ node:internal/process/task_queues:137
```

**Comment by davejorg** [comment] 2023-10-29 17:26
> I'm having the same problem.  I'm running Text Generator 0.3.20
> 
> 
> 
> I click on the "Text Generator: Templates Package Manager" button.  I see the following (which I think is what should happen):
> 
> ![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/3760075/221baa4c-9fe1-4aa7-8eb4-3f8baba1b568)
> 
> I cleared the developer console and then clicked on the "Huggingface Prompts Package" button.  I can see that another dialog with the prompt packages on the left side briefly shows and then the screen goes blank.
> 
> 
> 
> Here's a copy of the stack trace the occurs.

Based on the 2nd line of the stack trace - Please try disabling the plugin: "metadata-menu" and try again.

This worked for me. See my post a few comments up.

**Comment by Smitty010** [comment] 2023-10-29 17:43
So, I disabled the "metdata menu" plugin and tried it.  That allowed me to download the other template packages.  However, metadata menu is a part of my work flow so I've reenabled it.  I'm concerned that there may be other problems with TG with it enabled.  It seems like the conflict should be resolved.  I'm not sure who's problem it is to fix, but either "metadata menu" or "text generator" should determine what the issue is and fix it.

**Comment by davejorg** [comment] 2023-10-29 19:05
I'd recommend to re-enable the plug-in and see if it produces any conflicts. It seems the conflict only happens when the prompt packages are attempting to be downloaded, so I think you'll be good to enable once they are downloaded.

It's good to remember that it's not the creator of metadata-menu or text-expanders responsibility to fix any problem unless they determine it to be a priority. I always remind myself these people were very generous with their time to create these free tools that we get value from. 

If the problem persists, the most efficient options are to:

A) Troubleshoot the issue, offer to write a fix, write the fix, and submit a pull request for review and approval.

B) Troubleshoot the issue and submit a detailed bug report that isolates and describes the issue + thoughts on a likely fix as clearly as possible

C) Pay someone to complete option A) whether it's the original creator / contributor or someone external.

None of these options without the creator or contributors agreeing to fix it guarantees the fix will be accepted though.  

Hope this helps to get everything functional again.

**Comment by Comprehensive-Jason** [comment] 2023-11-07 14:39
Has this been fixed in the latest update 0.5.12 for y'all? I installed Readwise and Metadata Menu in my sandbox vault and didn't have this issue with the Package Manager anymore. 

Can someone else confirm so we can close this issue?

**Comment by haouarihk** [comment] 2023-12-29 15:52
i assume this issue has been resolved

feel free to reopen it

**Closed by haouarihk** 2023-12-29 15:52 UTC
Labels: bug

**Comment by aignaciodc** [comment] 2024-04-07 02:23
Just had this problem. I click on “default prompts package” and the screen flickers and goes back to home and…. nothing happens. But it’s locked up. Can’t click on anything, open/close files - nothing. Have to restart. I’ve tried waiting it out, like it’s installing, but nothing changes.
